# Generated by Django 5.1.7 on 2025-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilmlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfilmlist',
            name='username',
            field=models.CharField(default='temp_user', max_length=150),
        ),
    ]
