# Generated by Django 5.1.7 on 2025-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userfilmlist_user_id_userfilmlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilmlist',
            name='film_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userfilmlist',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
